### PR TITLE
Filter out non-GitHub-Action based checks

### LINKED ISSUE #6: Failed CodeQL actions break the rerun
### Describe the bug

When looking for check to re-run, it fails when there is a failed CodeQL check

### Version

0.1.0

### Expected behavior

Should only look at checks created from GitHub actions, as for example CodeQL check don't have a run associated.

### Actual behavior

Action aborts with an exception (404), as a job run for a CodeQL is not found.

### How to Reproduce?

Happend here: https://github.com/keycloak/keycloak/actions/runs/3043121332

### Anything else?

Will create a PR shortly.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #6

The error can be reproduced with the following minimal `event.json` file as long as the PR 14318 in the Keycloak main repository is unchanged.

```
{
  "action": "created",
  "comment": {
    "author_association": "OWNER",
    "body": "/rerun"
  },
  "issue": {
    "number": 14318,
    "author_association": "OWNER",
    "pull_request": {},
    "state": "open"
  },
  "repository": {
    "owner": {
      "login": "keycloak"
    },
    "name": "keycloak"
  }
}
```

This also shows that this is fixed: When running with my personal access token it continues further and then complains that I don't have permission to re-run the job (this is expected).

### CODE REVIEW

**Comment by ahus1** [comment]
@mabartos - I'd like to have this PR in before releasing a new version as this makes this action fail with the most recent changes to the checks in the main Keycloak repository.

Feel free to chip-in for a review on this.

**Review by mabartos — APPROVED** [review]
@ahus1 LGTM! Thanks!

File: index.js [hunk 1]
```diff
@@ -118,6 +125,10 @@ async function run() {
 
 run().catch((err) => {
   console.error(err);
+  console.log(
+    "Payload that triggered this error: ",
+    JSON.stringify(context.payload)
```
Comment (jonkoops) [inline index.js:130]: The console should be able to handle objects, so there is no need to serialize this.
```suggestion
    context.payload
```

File: README.md [hunk 2]
```diff
@@ -67,6 +67,26 @@ jobs:
 
 8. Create a PR for the main project.
 
+## Testing the GitHub action locally
```
Comment (jonkoops) [inline README.md:70]: A pretty common way to do this in Node applications is to use `.env` files. Not quite sure if it would work here but check out https://www.npmjs.com/package/dotenv.

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: index.js (hunk 1 above)
Comment (ahus1) [reply index.js:130]: I'd like to have the event in JSON format on the console, as only then it can be used for debugging purposed and put in to an `event.json` file. That's why I used `JSON.stringify`.

File: README.md (hunk 2 above)
Comment (ahus1) [reply README.md:70]: @jonkoops - I used it in other projects, yes that would be nice. 

After your comment I'd tested if this works with GitHub action packages, and it turns out it doesn't. Therefore I'd keep it as is for now.

Comment (jonkoops) [reply README.md:70]: Sounds good to me 👍

File: index.js (hunk 1 above)
Comment (jonkoops) [reply index.js:130]: But the console will format the JSON by default no?

Comment (ahus1) [reply index.js:130]: @jonkoops - when printing on the console, it will print curly braces, but will use the wrong quotes (single quotes instead of double quotes), and will not put quotes around the keys that JSON would require. So the default will print `action: 'created'` when JSON requires `"action": "created"`.
So that's why I added an explicit call to JSON.

Comment (jonkoops) [reply index.js:130]: Seems valid for logging, but if we could still pretty-print this with:
```suggestion
    JSON.stringify(context.payload, null, 2)
```

WDYT?

**Review by jonkoops — APPROVED** [review]
