### PR TITLE
Re-trigger run only once, even if multiple actions have failed

### LINKED ISSUE #15: When multiple steps in a workflow failed, trigger rerun only only once per workflow
### Describe the bug

When multiple steps in a workflow failed, the action fails as it tries to trigger the workflow for each failed action.

### Version

v0.3.0

### Expected behavior

Should re-run failed action only once per workflow. 

### Actual behavior

Trigger the workflow for each failed action.

### How to Reproduce?

Have a workflow with two failed steps. 

```
Payload that triggered this error:  {"action":"created","comment":{"author_association":"CONTRIBUTOR","body":"/rerun","created_at":"2022-10-18T21:50:48Z","html_url":"https://github.com/keycloak/keycloak/pull/14944#issuecomment-1283047002","id":1283047002,"issue_url":"https://api.github.com/repos/keycloak/keycloak/issues/14944","node_id":"IC_kwDOAKnDVc5Meb5a","performed_via_github_app":null,"reactions":{"+1":0,"-1":0,"confused":0,"eyes":0,"heart":0,"hooray":0,"laugh":0,"rocket":0,"total_count":0,"url":"https://api.github.com/repos/keycloak/keycloak/issues/comments/1283047002/reactions"},"updated_at":"2022-10-18T21:50:48Z","url":"https://api.github.com/repos/keycloak/keycloak/issues/comments/1283047002","user":{"avatar_url":"https://avatars.githubusercontent.com/u/3957921?v=4","events_url":"[https://api.github.com/users/ahus1/events{/privacy}](https://api.github.com/users/ahus1/events%7B/privacy%7D)","followers_url":"https://api.github.com/users/ahus1/followers","following_url":"[https://api.github.com/users/ahus1/following{/other_user}](https://api.github.com/users/ahus1/following%7B/other_user%7D)","gists_url":"[https://api.github.com/users/ahus1/gists{/gist_id}](https://api.github.com/users/ahus1/gists%7B/gist_id%7D)","gravatar_id":"","html_url":"https://github.com/ahus1","id":3957921,"login":"ahus1","node_id":"MDQ6VXNlcjM5NTc5MjE=","organizations_url":"https://api.github.com/users/ahus1/orgs","received_events_url":"https://api.github.com/users/ahus1/received_events","repos_url":"https://api.github.com/users/ahus1/repos","site_admin":false,"starred_url":"[https://api.github.com/users/ahus1/starred{/owner}{/repo}](https://api.github.com/users/ahus1/starred%7B/owner%7D%7B/repo%7D)","subscriptions_url":"https://api.github.com/users/ahus1/subscriptions","type":"User","url":"https://api.github.com/users/ahus1"}},"issue":{"active_lock_reason":null,"assignee":{"avatar_url":"https://avatars.githubusercontent.com/u/3957921?v=4","events_url":"[https://api.github.com/users/ahus1/events{/privacy}](https://api.github.com/users/ahus1/events%7B/privacy%7D)","followers_url":"https://api.github.com/users/ahus1/followers","following_url":"[https://api.github.com/users/ahus1/following{/other_user}](https://api.github.com/users/ahus1/following%7B/other_user%7D)","gists_url":"[https://api.github.com/users/ahus1/gists{/gist_id}](https://api.github.com/users/ahus1/gists%7B/gist_id%7D)","gravatar_id":"","html_url":"https://github.com/ahus1","id":3957921,"login":"ahus1","node_id":"MDQ6VXNlcjM5NTc5MjE=","organizations_url":"https://api.github.com/users/ahus1/orgs","received_events_url":"https://api.github.com/users/ahus1/received_events","repos_url":"https://api.github.com/users/ahus1/repos","site_admin":false,"starred_url":"[https://api.github.com/users/ahus1/starred{/owner}{/repo}](https://api.github.com/users/ahus1/starred%7B/owner%7D%7B/repo%7D)","subscriptions_url":"https://api.github.com/users/ahus1/subscriptions","type":"User","url":"https://api.github.com/users/ahus1"},"assignees":[{"avatar_url":"https://avatars.githubusercontent.com/u/3957921?v=4","events_url":"[https://api.github.com/users/ahus1/events{/privacy}](https://api.github.com/users/ahus1/events%7B/privacy%7D)","followers_url":"https://api.github.com/users/ahus1/followers","following_url":"[https://api.github.com/users/ahus1/following{/other_user}](https://api.github.com/users/ahus1/following%7B/other_user%7D)","gists_url":"[https://api.github.com/users/ahus1/gists{/gist_id}](https://api.github.com/users/ahus1/gists%7B/gist_id%7D)","gravatar_id":"","html_url":"https://github.com/ahus1","id":3957921,"login":"ahus1","node_id":"MDQ6VXNlcjM5NTc5MjE=","organizations_url":"https://api.github.com/users/ahus1/orgs","received_events_url":"https://api.github.com/users/ahus1/received_events","repos_url":"https://api.github.com/users/ahus1/repos","site_admin":false,"starred_url":"[https://api.github.com/users/ahus1/starred{/owner}{/repo}](https://api.github.com/users/ahus1/starred%7B/owner%7D%7B/repo%7D)","subscriptions_url":"https://api.github.com/users/ahus1/subscriptions","type":"User","url":"https://api.github.com/users/ahus1"}],"author_association":"CONTRIBUTOR","body":"Closes #14938\r\n\r\nCache hits and misses can be checked via the following conditional breakpoints in \r\n\r\nResults: \r\n\r\n* Login/Logout on Account console: no hits (two ignored due to dirty session)\r\n* Listing clients in admin UI: 13 misses, 39 hits\r\n* Listing client scopes in admin UI: 19 misses, 5 hits\r\n* Listing users in admin UI: 28 misses, 16 hits\r\n* Listing realm roles in admin UI: 13 misses, 2 hits \r\n\r\n<!---\r\nPlease read https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md and follow these guidelines when contributing to Keycloak\r\n-->\r\n","closed_at":null,"comments":1,"comments_url":"https://api.github.com/repos/keycloak/keycloak/issues/14944/comments","created_at":"2022-10-17T16:47:19Z","draft":true,"events_url":"https://api.github.com/repos/keycloak/keycloak/issues/14944/events","html_url":"https://github.com/keycloak/keycloak/pull/14944","id":1411894063,"labels":[{"color":"C5DEF5","default":false,"description":"Indicates an issue that touches storage (change in data layout or data manipulation)","id":2179403725,"name":"area/storage","node_id":"MDU6TGFiZWwyMTc5NDAzNzI1","url":"https://api.github.com/repos/keycloak/keycloak/labels/area/storage"},{"color":"FEF2C0","default":false,"description":"","id":3528867245,"name":"team/storage-sig","node_id":"LA_kwDOAKnDVc7SVj2t","url":"https://api.github.com/repos/keycloak/keycloak/labels/team/storage-sig"}],"labels_url":"[https://api.github.com/repos/keycloak/keycloak/issues/14944/labels{/name}](https://api.github.com/repos/keycloak/keycloak/issues/14944/labels%7B/name%7D)","locked":false,"milestone":null,"node_id":"PR_kwDOAKnDVc5A8mOa","number":14944,"performed_via_github_app":null,"pull_request":{"diff_url":"https://github.com/keycloak/keycloak/pull/14944.diff","html_url":"https://github.com/keycloak/keycloak/pull/14944","merged_at":null,"patch_url":"https://github.com/keycloak/keycloak/pull/14944.patch","url":"https://api.github.com/repos/keycloak/keycloak/pulls/14944"},"reactions":{"+1":0,"-1":0,"confused":0,"eyes":0,"heart":0,"hooray":0,"laugh":0,"rocket":0,"total_count":0,"url":"https://api.github.com/repos/keycloak/keycloak/issues/14944/reactions"},"repository_url":"https://api.github.com/repos/keycloak/keycloak","state":"open","state_reason":null,"timeline_url":"https://api.github.com/repos/keycloak/keycloak/issues/14944/timeline","title":"First naïve per-session caching for JPA map store","updated_at":"2022-10-18T21:50:48Z","url":"https://api.github.com/repos/keycloak/keycloak/issues/14944","user":{"avatar_url":"https://avatars.githubusercontent.com/u/3957921?v=4","events_url":"[https://api.github.com/users/ahus1/events{/privacy}](https://api.github.com/users/ahus1/events%7B/privacy%7D)","followers_url":"https://api.github.com/users/ahus1/followers","following_url":"[https://api.github.com/users/ahus1/following{/other_user}](https://api.github.com/users/ahus1/following%7B/other_user%7D)","gists_url":"[https://api.github.com/users/ahus1/gists{/gist_id}](https://api.github.com/users/ahus1/gists%7B/gist_id%7D)","gravatar_id":"","html_url":"https://github.com/ahus1","id":3957921,"login":"ahus1","node_id":"MDQ6VXNlcjM5NTc5MjE=","organizations_url":"https://api.github.com/users/ahus1/orgs","received_events_url":"https://api.github.com/users/ahus1/received_events","repos_url":"https://api.github.com/users/ahus1/repos","site_admin":false,"starred_url":"[https://api.github.com/users/ahus1/starred{/owner}{/repo}](https://api.github.com/users/ahus1/starred%7B/owner%7D%7B/repo%7D)","subscriptions_url":"https://api.github.com/users/ahus1/subscriptions","type":"User","url":"https://api.github.com/users/ahus1"}},"organization":{"avatar_url":"https://avatars.githubusercontent.com/u/4921466?v=4","description":"Open Source Identity and Access Management For Modern Applications and Services","events_url":"https://api.github.com/orgs/keycloak/events","hooks_url":"https://api.github.com/orgs/keycloak/hooks","id":4921466,"issues_url":"https://api.github.com/orgs/keycloak/issues","login":"keycloak","members_url":"[https://api.github.com/orgs/keycloak/members{/member}](https://api.github.com/orgs/keycloak/members%7B/member%7D)","node_id":"MDEyOk9yZ2FuaXphdGlvbjQ5MjE0NjY=","public_members_url":"[https://api.github.com/orgs/keycloak/public_members{/member}](https://api.github.com/orgs/keycloak/public_members%7B/member%7D)","repos_url":"https://api.github.com/orgs/keycloak/repos","url":"https://api.github.com/orgs/keycloak"},"repository":{"allow_forking":true,"archive_url":"[https://api.github.com/repos/keycloak/keycloak/{archive_format}{/ref}](https://api.github.com/repos/keycloak/keycloak/%7Barchive_format%7D%7B/ref%7D)","archived":false,"assignees_url":"[https://api.github.com/repos/keycloak/keycloak/assignees{/user}](https://api.github.com/repos/keycloak/keycloak/assignees%7B/user%7D)","blobs_url":"[https://api.github.com/repos/keycloak/keycloak/git/blobs{/sha}](https://api.github.com/repos/keycloak/keycloak/git/blobs%7B/sha%7D)","branches_url":"[https://api.github.com/repos/keycloak/keycloak/branches{/branch}](https://api.github.com/repos/keycloak/keycloak/branches%7B/branch%7D)","clone_url":"https://github.com/keycloak/keycloak.git","collaborators_url":"[https://api.github.com/repos/keycloak/keycloak/collaborators{/collaborator}](https://api.github.com/repos/keycloak/keycloak/collaborators%7B/collaborator%7D)","comments_url":"[https://api.github.com/repos/keycloak/keycloak/comments{/number}](https://api.github.com/repos/keycloak/keycloak/comments%7B/number%7D)","commits_url":"[https://api.github.com/repos/keycloak/keycloak/commits{/sha}](https://api.github.com/repos/keycloak/keycloak/commits%7B/sha%7D)","compare_url":"[https://api.github.com/repos/keycloak/keycloak/compare/{base}...{head}](https://api.github.com/repos/keycloak/keycloak/compare/%7Bbase%7D...%7Bhead%7D)","contents_url":"[https://api.github.com/repos/keycloak/keycloak/contents/{+path}](https://api.github.com/repos/keycloak/keycloak/contents/%7B+path%7D)","contributors_url":"https://api.github.com/repos/keycloak/keycloak/contributors","created_at":"2013-07-02T13:38:51Z","default_branch":"main","deployments_url":"https://api.github.com/repos/keycloak/keycloak/deployments","description":"Open Source Identity and Access Management For Modern Applications and Services","disabled":false,"downloads_url":"https://api.github.com/repos/keycloak/keycloak/downloads","events_url":"https://api.github.com/repos/keycloak/keycloak/events","fork":false,"forks":4805,"forks_count":4805,"forks_url":"https://api.github.com/repos/keycloak/keycloak/forks","full_name":"keycloak/keycloak","git_commits_url":"[https://api.github.com/repos/keycloak/keycloak/git/commits{/sha}](https://api.github.com/repos/keycloak/keycloak/git/commits%7B/sha%7D)","git_refs_url":"[https://api.github.com/repos/keycloak/keycloak/git/refs{/sha}](https://api.github.com/repos/keycloak/keycloak/git/refs%7B/sha%7D)","git_tags_url":"[https://api.github.com/repos/keycloak/keycloak/git/tags{/sha}](https://api.github.com/repos/keycloak/keycloak/git/tags%7B/sha%7D)","git_url":"git://github.com/keycloak/keycloak.git","has_downloads":true,"has_issues":true,"has_pages":false,"has_projects":true,"has_wiki":false,"homepage":"https://www.keycloak.org/","hooks_url":"https://api.github.com/repos/keycloak/keycloak/hooks","html_url":"https://github.com/keycloak/keycloak","id":11125589,"is_template":false,"issue_comment_url":"[https://api.github.com/repos/keycloak/keycloak/issues/comments{/number}](https://api.github.com/repos/keycloak/keycloak/issues/comments%7B/number%7D)","issue_events_url":"[https://api.github.com/repos/keycloak/keycloak/issues/events{/number}](https://api.github.com/repos/keycloak/keycloak/issues/events%7B/number%7D)","issues_url":"[https://api.github.com/repos/keycloak/keycloak/issues{/number}](https://api.github.com/repos/keycloak/keycloak/issues%7B/number%7D)","keys_url":"[https://api.github.com/repos/keycloak/keycloak/keys{/key_id}](https://api.github.com/repos/keycloak/keycloak/keys%7B/key_id%7D)","labels_url":"[https://api.github.com/repos/keycloak/keycloak/labels{/name}](https://api.github.com/repos/keycloak/keycloak/labels%7B/name%7D)","language":"Java","languages_url":"https://api.github.com/repos/keycloak/keycloak/languages","license":{"key":"apache-2.0","name":"Apache License 2.0","node_id":"MDc6TGljZW5zZTI=","spdx_id":"Apache-2.0","url":"https://api.github.com/licenses/apache-2.0"},"merges_url":"https://api.github.com/repos/keycloak/keycloak/merges","milestones_url":"[https://api.github.com/repos/keycloak/keycloak/milestones{/number}](https://api.github.com/repos/keycloak/keycloak/milestones%7B/number%7D)","mirror_url":null,"name":"keycloak","node_id":"MDEwOlJlcG9zaXRvcnkxMTEyNTU4OQ==","notifications_url":"[https://api.github.com/repos/keycloak/keycloak/notifications{?since](https://api.github.com/repos/keycloak/keycloak/notifications%7B?since),all,participating}","open_issues":1367,"open_issues_count":1367,"owner":{"avatar_url":"https://avatars.githubusercontent.com/u/4921466?v=4","events_url":"[https://api.github.com/users/keycloak/events{/privacy}](https://api.github.com/users/keycloak/events%7B/privacy%7D)","followers_url":"https://api.github.com/users/keycloak/followers","following_url":"[https://api.github.com/users/keycloak/following{/other_user}](https://api.github.com/users/keycloak/following%7B/other_user%7D)","gists_url":"[https://api.github.com/users/keycloak/gists{/gist_id}](https://api.github.com/users/keycloak/gists%7B/gist_id%7D)","gravatar_id":"","html_url":"https://github.com/keycloak","id":4921466,"login":"keycloak","node_id":"MDEyOk9yZ2FuaXphdGlvbjQ5MjE0NjY=","organizations_url":"https://api.github.com/users/keycloak/orgs","received_events_url":"https://api.github.com/users/keycloak/received_events","repos_url":"https://api.github.com/users/keycloak/repos","site_admin":false,"starred_url":"[https://api.github.com/users/keycloak/starred{/owner}{/repo}](https://api.github.com/users/keycloak/starred%7B/owner%7D%7B/repo%7D)","subscriptions_url":"https://api.github.com/users/keycloak/subscriptions","type":"Organization","url":"https://api.github.com/users/keycloak"},"private":false,"pulls_url":"[https://api.github.com/repos/keycloak/keycloak/pulls{/number}](https://api.github.com/repos/keycloak/keycloak/pulls%7B/number%7D)","pushed_at":"2022-10-18T21:49:33Z","releases_url":"[https://api.github.com/repos/keycloak/keycloak/releases{/id}](https://api.github.com/repos/keycloak/keycloak/releases%7B/id%7D)","size":186426,"ssh_url":"git@github.com:keycloak/keycloak.git","stargazers_count":13828,"stargazers_url":"https://api.github.com/repos/keycloak/keycloak/stargazers","statuses_url":"[https://api.github.com/repos/keycloak/keycloak/statuses/{sha}](https://api.github.com/repos/keycloak/keycloak/statuses/%7Bsha%7D)","subscribers_url":"https://api.github.com/repos/keycloak/keycloak/subscribers","subscription_url":"https://api.github.com/repos/keycloak/keycloak/subscription","svn_url":"https://github.com/keycloak/keycloak","tags_url":"https://api.github.com/repos/keycloak/keycloak/tags","teams_url":"https://api.github.com/repos/keycloak/keycloak/teams","topics":["keycloak","oidc","saml"],"trees_url":"[https://api.github.com/repos/keycloak/keycloak/git/trees{/sha}](https://api.github.com/repos/keycloak/keycloak/git/trees%7B/sha%7D)","updated_at":"2022-10-18T19:01:24Z","url":"https://api.github.com/repos/keycloak/keycloak","visibility":"public","watchers":13828,"watchers_count":13828,"web_commit_signoff_required":false},"sender":{"avatar_url":"https://avatars.githubusercontent.com/u/3957921?v=4","events_url":"[https://api.github.com/users/ahus1/events{/privacy}](https://api.github.com/users/ahus1/events%7B/privacy%7D)","followers_url":"https://api.github.com/users/ahus1/followers","following_url":"[https://api.github.com/users/ahus1/following{/other_user}](https://api.github.com/users/ahus1/following%7B/other_user%7D)","gists_url":"[https://api.github.com/users/ahus1/gists{/gist_id}](https://api.github.com/users/ahus1/gists%7B/gist_id%7D)","gravatar_id":"","html_url":"https://github.com/ahus1","id":3957921,"login":"ahus1","node_id":"MDQ6VXNlcjM5NTc5MjE=","organizations_url":"https://api.github.com/users/ahus1/orgs","received_events_url":"https://api.github.com/users/ahus1/received_events","repos_url":"https://api.github.com/users/ahus1/repos","site_admin":false,"starred_url":"[https://api.github.com/users/ahus1/starred{/owner}{/repo}](https://api.github.com/users/ahus1/starred%7B/owner%7D%7B/repo%7D)","subscriptions_url":"https://api.github.com/users/ahus1/subscriptions","type":"User","url":"https://api.github.com/users/ahus1"}}
    at file:///home/runner/work/_actions/keycloak/keycloak-gh-actionbot/33d[8](https://github.com/keycloak/keycloak/actions/runs/3277174198/jobs/5394112203#step:2:9)75[9](https://github.com/keycloak/keycloak/actions/runs/3277174198/jobs/5394112203#step:2:10)517f1bfbb70d52fa1f6d58ef2e824301b/dist/index.js:22067:21
Error: Unexpected error
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.doExecute (file:///home/runner/work/_actions/keycloak/keycloak-gh-actionbot/33d8759517f1bfbb70d52fa1f6d58ef2e824301b/dist/index.js:12900:18) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/keycloak/keycloak/actions/runs/3274319554/rerun-failed-jobs',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 18 Oct 2022 21:51:00 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '0406:0E7A:1751AFD:2FDE20B:634F1FC4',
      'x-ratelimit-limit': '[10](https://github.com/keycloak/keycloak/actions/runs/3277174198/jobs/5394112203#step:2:11)00',
      'x-ratelimit-remaining': '985',
      'x-ratelimit-reset': '1666[12](https://github.com/keycloak/keycloak/actions/runs/3277174198/jobs/5394112203#step:2:13)9936',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '15',
      'x-xss-protection': '0'
    },
    data: {
      message: 'This workflow is already running',
      documentation_url: 'https://docs.github.com/rest/reference/actions#re-run-workflow-failed-jobs'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/keycloak/keycloak/actions/runs/3274319554/rerun-failed-jobs',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/2.0.7 octokit-core.js/4.0.5 Node.js/16.[13](https://github.com/keycloak/keycloak/actions/runs/3277174198/jobs/5394112203#step:2:14).0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-length': 0
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #15

### CODE REVIEW

**Comment by ahus1** [comment]
Hi @jonkoops - I'd be happy if you could review this PR. Thanks!

File: index.js [hunk 1]
```diff
@@ -100,13 +102,22 @@ async function run() {
           console.log("Job:", job);
         }
 
+        if (restarted_runs.has(job.run_id)) {
+          if (debug) {
+            console.log("Ignoring this job as run_id already restarted");
+          }
```
Comment (jonkoops) [inline index.js:108]: Unrelated to this PR. But perhaps we should create a logger API that will handle the `debug` condition consistently.

**Review by jonkoops — APPROVED** [review]

File: index.js (hunk 1 above)
Comment (ahus1) [reply index.js:108]: Thanks for noting that. Let's see if this bot would eventually be integrated to https://github.com/keycloak/keycloak-github-bot
